@startuml

title impedance mismatch\n(임피던스 불일치)

node "애플리케이션"{
    [객체형 데이터]
}

database "RDB" {
  [관계형 데이터]
}

[전환 계층]

[객체형 데이터] --> [전환 계층]
[관계형 데이터] <-- [전환 계층]
[관계형 데이터] --> [전환 계층]
[객체형 데이터] <-- [전환 계층]

@enduml